# Generated by Django 3.2 on 2021-04-20 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nora', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_delivery_after',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryMethod', models.CharField(max_length=100)),
                ('cartItemDetails', models.CharField(max_length=10000)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=110)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
