# Generated by Django 3.2 on 2021-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0008_auto_20210420_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='deliveryDate',
            field=models.CharField(default='2 days from today', max_length=300),
        ),
    ]
