# Generated by Django 3.2 on 2021-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0009_counter_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='phone',
            field=models.CharField(default='client_number', max_length=20),
        ),
    ]
