# Generated by Django 3.2 on 2021-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0010_counter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='deliveryDate',
            field=models.DateTimeField(default='2 days from today', max_length=300),
        ),
    ]
