# Generated by Django 3.2 on 2021-04-21 05:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nora', '0011_alter_counter_deliverydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryMethod', models.CharField(max_length=100)),
                ('cartItemDetails', models.CharField(max_length=10000)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=110)),
                ('deliveryDate', models.DateTimeField(default=datetime.datetime(2021, 4, 21, 6, 4, 58, 322128))),
                ('phone', models.CharField(default='client_number', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deliveryDate'],
            },
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
