# Generated by Django 3.2 on 2021-04-22 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0012_auto_20210421_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='order_stage',
            field=models.CharField(choices=[('Order placed', 'Order Placed'), ('Processing', 'In transit'), ('Delivered', 'Delivered')], default='Order placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='desk',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 6, 25, 40, 459378)),
        ),
    ]
