# Generated by Django 3.2 on 2021-04-22 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0017_auto_20210422_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 13, 54, 28, 224456)),
        ),
    ]
